// ACTION TYPES
export const actionTypes = {
	CHANGE_LOCALE: 'CHANGE_LOCALE',
	CHANGE_LOCALE_LANGS: 'CHANGE_LOCALE_LANGS',	
	LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
	LOG_IN_FAILURE: 'LOG_IN_FAILURE',
	AUTH_FAILURE: 'AUTH_FAILURE',
	LOGGED_OFF: 'LOGGED_OFF',

	CHANGE_SEAERCH_FILTER: 'CHANGE_SEAERCH_FILTER',
	CHANGE_SEAERCH_QUERY: 'CHANGE_SEAERCH_QUERY',
	CHANGE_SEAERCH_PAGE: 'CHANGE_SEAERCH_PAGE',
	CHANGE_SEAERCH_SIZE: 'CHANGE_SEAERCH_SIZE',
	CHANGE_SEAERCH_SORT: 'CHANGE_SEAERCH_SORT'
	
};
